# The name of the environment matching the repository name
name: angel.co_scrapper
# I prefer conda-forge packages for my projects
channels:
  - conda-forge
  - defaults
# Start with Python and include everything you need
dependencies:
  - python=3.7
  - pip
  - numpy
  - alabaster==0.7.12
  - anaconda-client==1.7.2
  - anaconda-project==0.8.3
  - argh==0.26.2
  - selenium
pip:
  - bs4
